.\" Copyright Petr Hracek, 2013
.\"
.\" This page is distributed under GPL.
.\"
.TH DA 1 2014-04-04 "" "Linux User's Manual"
.SH NAME
da-gui \- GUI for DevAssistant

.SH DESCRIPTION
GUI for DevAssistant. See man page for \fBda\fP (1).

.SH ENVIRONMENT
.TP
.B DevAssistant GUI
is run when X server is running and environment variable DISPLAY is set.
.SH "SEE ALSO"
.BR da (1)
